name: UltraItems
version: ${project.version}
author: Lisured
depend: [Spout]
description: Create custom textured items with click action.
main: cz.ogion.ultraitems.UltraItems
commands:
  ultraitems:
    description: Provides functions to reload the config.
    usage: |
      /ultraitems reload
      /ultraitems list
      /ultraitems replace
      /ultraitems <itemname> [amount]
    aliases: [ui]
permissions:
    ultraitems.*:
        description: All UltraItems' commands
        children:
            ultraitem.reload: true
            ultraitem.list: true
            ultraitem.give: true
            ultraitem.give.*: true
            ultraitem.craft.*: true
    ultraitems.reload:
        description: Reload config
        default: op
    ultraitems.list:
        description: Show list of items
        default: true
    ultraitems.give:
        description: Give item
        default: true
    ultraitems.give.*:
        description: Give all items
        default: true
    ultraitems.craft.*:
        description: Craft all items
        default: true
